[package]
name = "observlib"
version = "0.1.0"
edition = "2024"

[lib]
name = "observlib"
path = "src/lib/mod.rs"

[dependencies]
opentelemetry = "0.31.0"
opentelemetry_api = "0.20.0"
opentelemetry_sdk = "0.31.0"
